fits:
  - name: "projX"
    projRange: 
      - 0
      - -1
    rebin: 32
    func: "[0] * exp(-(x-[1])**2 / (2 * [2]**2))" 
    range: 
      - 448
      - 650
    nParams: 3
    param:
      - 3500
      - 540
      - 70
    color: 2

  - name: "projY"
    projRange: 
      - 1040
      - 1150
    rebin: 32
    func: "[0] * exp(-(x-[1])**2 / (2 * [2]**2))" 
    range: 
      - 150
      - 336
    nParams: 3
    param:
      - 1300
      - 226
      - 60
    color: 3