// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /Users/giogi/Documents/LabFNS2/./Beta/src/analysis.h;
#pragma link C++ defined_in "/Users/giogi/Documents/LabFNS2/./Beta/src/analysis.C";

#endif
